export default {
  LOAD_CURRENT_USER_DATA: "LOAD_CURRENT_USER_DATA",
  SET_CURRENT_USER_DATA: "SET_CURRENT_USER_DATA",
  SET_CURRENT_USER_ERROR: "SET_CURRENT_USER_ERROR",

  CREATE_USER_BY_EMAIL: "CREATE_USER_BY_EMAIL",
  CREATE_USER_BY_EMAIL_SUCCESS: "CREATE_USER_BY_EMAIL_SUCCESS",
  CREATE_USER_BY_EMAIL_ERROR: "CREATE_USER_BY_EMAIL_ERROR",
};
